appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: R947Ue7ms6dAGSXzaqfGXI2FmqZtwrK88bW9SRX5Gazf+HTIcuhJIcxmZPHg8AzE8OkQxZZ6mFTixm4HUq2ANmMo5A0YhBGmH9+A1BCTkzwNFiR5RZYiOGQEjPZnjPhC378+llr2K3vBg1YzUz0qfpy2Xvk2vNxYFE9brTMyaYn87fE1nzp+TFZC5B8RVSX/BFSkOl/KDsYGcG14+4AuxSo1Gjqrod7g4AcwMoLO36o8CYcU3Org7O3HTVYdaVGsQ3QfMcrR2VtxvyT0zDFglE19CN/+EqnAOuh1FmMI7kUlsj4QGDQnZRC450852og2KU2pn7IXa3Jhbrh4CrZngZSzpGC0AIZR1O2whvp9B0cxWTCT+AyW/p8OhkN64wX8bZH1VVmHpPZ9ma8GK1LfEp1fyD8/769LjuO5vw2iUmfnOn2KdoRzwTfavaSyemywALvgG4YZpsmIQbjiuKufr8GtraL7QrXTq4ALmptIWVHEDrYBkQqz7j6SdPDEzgqUOqYQH+gdqUpsSWKxLmAqrjgQlscPO5ogR7CYqyFmyKiakYyB1VzoO7czYFCi1TQ1o5sW+OdX+hKvSKq9x/z4SnP/+KgppUS6LSvihzCG1laVvksVfko5NWml7qrB2EbwyWW8hGvSW9OHdQZOl8psyqdkJTBTdiI+TwPT1SECygY=}
